Repository tusharchou/local-data-platform, pull requests merged in 2024-10, with the labels that each got.

#18 Chore: Code clean up
  .idea/.gitignore
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/local-data-platform.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
Labels: bug

#25 0.1.1 19 local_data_platform.source.near.bigquery.get(query)
  .gitignore
  local-data-platform/local_data_platform/source/gcp/__init__.py
  local-data-platform/local_data_platform/source/gcp/gcp_bigquery/__init__.py
  local-data-platform/local_data_platform/source/gcp/gcp_bigquery/source_gcp_bigquery.py
  local-data-platform/local_data_platform/source/gcp/gcp_connection.py
  local-data-platform/local_data_platform/source/near/near_transactions.sql
  local-data-platform/local_data_platform/source/near/source_near_gcp.py
  local-data-platform/poetry.lock
  local-data-platform/pyproject.toml
  local-data-platform/tests/test_gcp_connection.py
Labels: enhancement, help wanted, good first issue, good first review

#26 0.1.1 24 local_data_platform.target.local.iceberg.put(dataframe)
  .gitignore
  .readthedocs.yaml
  local-data-platform/local_data_platform/__init__.py
  local-data-platform/local_data_platform/catalog/sql.py
  local-data-platform/local_data_platform/source/gcp/gcp_bigquery/source_gcp_bigquery.py
  local-data-platform/local_data_platform/source/gcp/gcp_connection.py
  local-data-platform/local_data_platform/source/near/near_transactions.sql
  local-data-platform/local_data_platform/source/near/source_near_gcp.py
  local-data-platform/local_data_platform/source/parquet/pyarrow_table.py
  local-data-platform/local_data_platform/target/__init__.py
  local-data-platform/local_data_platform/target/iceberg/__init__.py
  local-data-platform/local_data_platform/target/iceberg/table.py
  local-data-platform/nyc_yellow_taxi.py
  local-data-platform/nyc_yellow_taxi_ingestion.py
  local-data-platform/tests/test_gcp_connection.py
  local-data-platform/tmp/warehouse/pyiceberg_catalog.db
Labels: enhancement, help wanted, good first issue, good first review

#37 0.1.2 Testing pre release for 0.1.1
  LICENSE
  README.md
  README.rst
  docs/Makefile
  docs/api.rst
  docs/conf.py
  docs/index.rst
  docs/make.bat
  docs/requirements.in
  docs/requirements.txt
  docs/usage.rst
  lumache.py
  pyproject.toml
Labels: enhancement, good first review

#41 Readme Update
  README.md
Labels: documentation, good first review

#52 0.1.1 Supporting Iceberg Lakehouse Locally
  local-data-platform/local_data_platform/__init__.py
  local-data-platform/local_data_platform/engine/__init__.py
  local-data-platform/local_data_platform/exceptions.py
  local-data-platform/local_data_platform/format/__init__.py
  local-data-platform/local_data_platform/format/csv/__init__.py
  local-data-platform/local_data_platform/format/iceberg/__init__.py
  local-data-platform/local_data_platform/format/parquet/__init__.py
  local-data-platform/local_data_platform/logger.py
  local-data-platform/local_data_platform/pipeline/egression/__init__.py
  local-data-platform/local_data_platform/pipeline/egression/iceberg_to_csv/__init__.py
  local-data-platform/local_data_platform/pipeline/ingestion/__init__.py
  local-data-platform/local_data_platform/pipeline/ingestion/parquet_to_iceberg/__init__.py
  local-data-platform/local_data_platform/pipeline/ingestion/pyarrow/__init__.py
  local-data-platform/real_world_use_cases/nyc_yellow_taxi_dataset/config/egression.json
  local-data-platform/real_world_use_cases/nyc_yellow_taxi_dataset/config/ingestion.json
  local-data-platform/real_world_use_cases/nyc_yellow_taxi_dataset/monthly_reporting.py
Labels: bug, enhancement, question

#56 0.1.1 Added source class for GCP BigQuery
  .gitignore
  local-data-platform/local_data_platform/__init__.py
  local-data-platform/local_data_platform/__pycache__/__init__.cpython-312.pyc
  local-data-platform/local_data_platform/__pycache__/hello_world.cpython-312.pyc
  local-data-platform/local_data_platform/catalog/local/iceberg/__init__.py
  local-data-platform/local_data_platform/format/csv/__init__.py
  local-data-platform/local_data_platform/format/iceberg/__init__.py
  local-data-platform/local_data_platform/logger.py
  local-data-platform/local_data_platform/pipeline/__init__.py
  local-data-platform/local_data_platform/pipeline/egression/csv_to_iceberg/__init__.py
  local-data-platform/local_data_platform/pipeline/egression/iceberg_to_csv/__init__.py
  local-data-platform/local_data_platform/pipeline/ingestion/bigquery_to_csv/__init__.py
  local-data-platform/local_data_platform/pipeline/ingestion/csv_to_iceberg/__init__.py
  local-data-platform/local_data_platform/pipeline/ingestion/parquet_to_iceberg/__init__.py
  local-data-platform/local_data_platform/pipeline/ingestion/pyarrow/__init__.py
  local-data-platform/local_data_platform/source/gcp/gcp_bigquery/source_gcp_bigquery.py
  local-data-platform/local_data_platform/source/gcp/gcp_connection.py
  local-data-platform/local_data_platform/source/near/near_transactions.sql
  local-data-platform/local_data_platform/source/near/source_near_gcp.py
  local-data-platform/local_data_platform/store/source/gcp/__init__.py
  local-data-platform/local_data_platform/store/source/gcp/bigquery/__init__.py
  local-data-platform/local_data_platform/store/source/gcp/gcp_bigquery/__init__.py
  local-data-platform/local_data_platform/store/source/json/__init__.py
  local-data-platform/local_data_platform/store/target/iceberg/__init__.py
  local-data-platform/poetry.lock
  local-data-platform/pyproject.toml
  local-data-platform/real_world_use_cases/near_data_lake/config/egression.json
  local-data-platform/real_world_use_cases/near_data_lake/config/ingestion.json
  local-data-platform/real_world_use_cases/near_data_lake/config/sample_queries/near_transaction.json
  local-data-platform/real_world_use_cases/near_data_lake/monthly_reporting.py
  local-data-platform/real_world_use_cases/near_data_lake/near_transactions.csv
  local-data-platform/tests/test_gcp_connection.py
  samples/bigQueryTutorial.py
Labels: enhancement, good first issue, good first review

#58 V0.1.1
  local-data-platform/local_data_platform/__init__.py
  local-data-platform/local_data_platform/catalog/local/iceberg/__init__.py
  local-data-platform/local_data_platform/format/csv/__init__.py
  local-data-platform/local_data_platform/format/iceberg/__init__.py
  local-data-platform/local_data_platform/format/parquet/__init__.py
  local-data-platform/local_data_platform/logger.py
  local-data-platform/local_data_platform/pipeline/__init__.py
  local-data-platform/local_data_platform/pipeline/egression/iceberg_to_csv/__init__.py
  local-data-platform/local_data_platform/pipeline/ingestion/__init__.py
  local-data-platform/local_data_platform/pipeline/ingestion/csv_to_iceberg/__init__.py
  local-data-platform/local_data_platform/pipeline/ingestion/parquet_to_iceberg/__init__.py
  local-data-platform/local_data_platform/store/source/gcp/__init__.py
  local-data-platform/real_world_use_cases/near_data_lake/reports/get_data.py
  local-data-platform/real_world_use_cases/near_data_lake/reports/put_data.py
  local-data-platform/real_world_use_cases/nyc_yellow_taxi_dataset/config/egression.json
  local-data-platform/real_world_use_cases/nyc_yellow_taxi_dataset/config/ingestion.json
  local-data-platform/real_world_use_cases/nyc_yellow_taxi_dataset/monthly_reporting.md
  local-data-platform/real_world_use_cases/nyc_yellow_taxi_dataset/monthly_reporting.py
  local-data-platform/real_world_use_cases/nyc_yellow_taxi_dataset/reports/get_data.py
  local-data-platform/real_world_use_cases/nyc_yellow_taxi_dataset/reports/put_data.py
Labels: Maintenance

#46 0.1.1 BigQuery Release
  .github/workflows/publish.yml
Labels: enhancement, question

#60 pypi release through github actions
  .github/workflows/publish.yml
Labels: Maintenance

#66 Update publish.yml
  .github/workflows/publish.yml
Labels: bug

#67 Brmhastra patch 1
  .github/workflows/publish.yml
Labels: bug

#69 Brmhastra patch 1
  .github/workflows/publish.yml
Labels: bug

#73 Github actions setup for release v1.1
  .github/workflows/publish.yml
Labels: Maintenance

#74 Release v1.1 changes
  .github/workflows/publish.yml
  local-data-platform/dist/local_data_platform-0.1.1-py3-none-any.whl
  local-data-platform/dist/local_data_platform-0.1.1.tar.gz
Labels: Maintenance

#76 Github action setup for release v1.1
  .github/workflows/publish.yml
Labels: Maintenance
